Add format string literal to panic
Without this change, `cargo build` gives the following error.

```
error: format argument must be a string literal
   --> src\main.rs:175:16
    |
175 |         panic!(io::Error::last_os_error());
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: you might be missing a string literal to format with
    |
175 |         panic!("{}", io::Error::last_os_error());
    |                +++++
```

The above error is given by rustc 1.62.1 (e092d0b6b 2022-07-16)